// Runtime accessor for LLM-enriched college majors.
//
// The JSON file at src/data/college-majors.json is generated by
// `npm run enrich:colleges` (see scripts/enrich-college-majors.ts). It
// holds 5-8 topMajors and 3-6 knownFor entries per school plus validation
// metadata (needsReview, droppedMajors, warnings).
//
// This module:
//   1. Imports the JSON via TypeScript's resolveJsonModule (bundles into
//      the client at build time).
//   2. Filters out rows flagged needsReview = true so they never affect
//      live scoring until an operator manually clears the flag.
//   3. Provides a tiny lookup helper consumed by major-match.ts.
//
// Forward-compat: an empty stub is committed so the import resolves on a
// fresh checkout that hasn't run the enrichment script yet. In that case
// every lookup returns null and the matcher falls back to curated-only
// behavior — identical to pre-enrichment scoring.

import enrichedRaw from "../data/college-majors.json";

interface EnrichedSchoolEntry {
  readonly topMajors: readonly string[];
  readonly knownFor: readonly string[];
  readonly confidence?: number;
  readonly notes?: string;
  readonly needsReview?: boolean;
  readonly droppedMajors?: readonly string[];
  readonly warnings?: readonly string[];
}

interface EnrichedFile {
  readonly schemaVersion: number;
  readonly schools: Readonly<Record<string, EnrichedSchoolEntry>>;
}

const SUPPORTED_SCHEMA_VERSION = 2;

const file = enrichedRaw as EnrichedFile;

// Refuse to consume an unknown schema version. Returning empty data here
// keeps the matcher in curated-only mode rather than reading fields that
// may have shifted shape.
const schools: Readonly<Record<string, EnrichedSchoolEntry>> =
  file.schemaVersion === SUPPORTED_SCHEMA_VERSION ? file.schools : {};

export interface EnrichedMajors {
  readonly topMajors: readonly string[];
  readonly knownFor: readonly string[];
}

/**
 * Look up enriched majors data for a college by exact name match.
 *
 * Returns null when:
 *   - the school isn't in the enriched dataset (e.g. before the script
 *     has been run for this school)
 *   - the row is flagged needsReview = true (low LLM confidence; spec
 *     says these are excluded from runtime scoring until cleared)
 */
export function getEnrichedMajors(collegeName: string): EnrichedMajors | null {
  const entry = schools[collegeName];
  if (!entry) return null;
  if (entry.needsReview === true) return null;
  return {
    topMajors: entry.topMajors ?? [],
    knownFor: entry.knownFor ?? [],
  };
}

/**
 * Subtract curated entries from a list (case-insensitive EQUALITY only).
 * Used by major-match.ts to identify the "enriched-only" pool — entries
 * the LLM added that aren't exact duplicates of hand-curated entries.
 *
 * Why exact equality and not substring? "Hand-curated wins on conflict"
 * means same-entry conflicts. A curated parent like "Engineering" and an
 * enriched specific like "Biomedical Engineering" are NOT a conflict —
 * the enriched specific genuinely adds resolution that the curated record
 * lacked. Filtering by substring would silently throw that away.
 */
export function enrichedOnlyEntries(
  enrichedList: readonly string[],
  curatedList: readonly string[] | undefined,
): string[] {
  if (!enrichedList.length) return [];
  if (!curatedList || curatedList.length === 0) return [...enrichedList];
  const curatedLower = new Set(curatedList.map((c) => c.toLowerCase()));
  return enrichedList.filter((e) => !curatedLower.has(e.toLowerCase()));
}
