import type { GradingResult } from "./types";

/**
 * Convert a GradingResult into a human-readable Markdown report and
 * trigger a browser download.
 */
export function exportGradeAsMarkdown(essayText: string, result: GradingResult): void {
  const md = buildMarkdownReport(essayText, result);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const date = new Date().toISOString().slice(0, 10);
  a.download = `essay-grade-${date}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function buildMarkdownReport(essayText: string, r: GradingResult): string {
  const date = new Date().toLocaleDateString(undefined, {
    year: "numeric", month: "long", day: "numeric",
  });

  const common = Object.entries(r.commonApp)
    .map(([name, v]) => `### ${name}: ${v.score}/100\n\n${v.feedback}`)
    .join("\n\n");

  const vspice = Object.entries(r.vspice)
    .map(([name, v]) => `### ${name}: ${v.score}/4\n\n${v.feedback}`)
    .join("\n\n");

  const bonuses = r.bonuses && r.bonuses.length > 0
    ? r.bonuses.map((b) => `- ${b}`).join("\n")
    : "_None detected._";

  const pitfalls = r.pitfalls && r.pitfalls.length > 0
    ? r.pitfalls.map((p) => `- ${p}`).join("\n")
    : "_None detected._";

  const lineSuggestions = r.lineSuggestions && r.lineSuggestions.length > 0
    ? r.lineSuggestions
        .map((s, i) => `**${i + 1}.** > ${s.line}\n\n${s.suggestion}`)
        .join("\n\n")
    : "_No line-specific suggestions._";

  return `# Essay Grade Report

**Date:** ${date}
**Word count:** ${r.wordCount}
**Raw Score:** ${r.rawScore} / 100
**Adjusted Score:** ${r.adjustedScore} / 100${r.wordCountPenalty > 0 ? `  _(−${r.wordCountPenalty} word-count penalty)_` : ""}
**VSPICE Composite:** ${r.vspiceComposite} / 24

---

## Common App Criteria

${common}

---

## VSPICE Character Rubric

${vspice}

---

## Bonuses

${bonuses}

## Pitfalls

${pitfalls}

---

## Line-Specific Suggestions

${lineSuggestions}

---

## Overall Feedback

${r.generalFeedback}

---

## Essay

${essayText}

---

_Generated by AdmitEdge Essay Grader. AI-generated scores are estimates — use as a revision tool, not official admissions feedback._
`;
}
