/**
 * school-data.ts
 *
 * Reads the imported per-feeder-school history JSON and blends it into the
 * national chance model. The data file is generated by
 * scripts/import-school-data.ts from a Scoir CSV (currently synthetic; real
 * counselor CSV when it arrives).
 *
 * Design notes:
 * - The blend is opt-in per school: missing record OR sample <5 returns the
 *   national chance unchanged.
 * - schoolWeight is capped at 0.5. Even with hundreds of applicants we don't
 *   trust a single feeder school's history more than the broader CDS-grounded
 *   model — small feeder schools have peer effects that don't generalize.
 * - The percentile multiplier S-curve is rule-of-thumb. Anchors (0.3/1.0/2.5)
 *   are picked so a top-decile applicant sees ~2.5x the school's raw admit
 *   rate, a median applicant sees the raw rate, and a bottom-decile applicant
 *   sees ~0.3x.
 */
import type { ApplicationPlan, College } from "./college-types";

// ── Slug ─────────────────────────────────────────────────────────────────────
// Must match scripts/import-school-data.ts toSlug exactly. Centralized here
// so the model and the importer can't drift.
export function toCollegeSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// ── Types (mirror the importer's AggregateRecord) ────────────────────────────
export interface SchoolDataRecord {
  readonly collegeName: string;
  readonly collegeSlug: string;
  readonly appType: string;
  readonly totalApplicants: number;
  readonly totalAdmits: number;
  readonly totalDenied: number;
  readonly totalWaitlisted: number;
  readonly schoolAdmitRate: number;          // 0-1 (note: NOT 0-100)
  readonly admittedAvgGPA: number | null;
  readonly admittedAvgSAT: number | null;
  readonly admittedAvgACT: number | null;
  readonly admittedGPARange: readonly [number, number] | null;
  readonly admittedSATRange: readonly [number, number] | null;
  readonly admittedStdGPA: number | null;
  readonly admittedStdSAT: number | null;
  readonly rawDataPoints: readonly {
    readonly gpaWeighted: number | null;
    readonly sat: number | null;
    readonly act: number | null;
    readonly outcome: "Accepted" | "Denied" | "Waitlisted";
    readonly classYear: number;
  }[];
  readonly sampleSizeLabel: "limited" | "moderate" | "strong";
}

type SchoolDataIndex = Record<string, Record<string, SchoolDataRecord>>;

// Deferred import. Webpack/Next will inline the JSON at build time. The
// double-cast through `unknown` is needed because TS infers tuple-typed
// fields like admittedGPARange as `number[]` from JSON, which doesn't match
// the readonly tuple shape on SchoolDataRecord.
import schoolDataRaw from "@/data/school-specific-data.json";
const SCHOOL_DATA = schoolDataRaw as unknown as SchoolDataIndex;

// Test-time override. Set by the scenario runner so we can swap in synthetic
// per-school history without touching the committed JSON. Production code
// never sets this.
let TEST_OVERRIDE: SchoolDataIndex | null = null;

export function _setSchoolDataOverrideForTesting(index: SchoolDataIndex | null): void {
  TEST_OVERRIDE = index;
}

// ── Lookup ───────────────────────────────────────────────────────────────────
export function getSchoolRecord(
  college: College,
  plan: ApplicationPlan,
): SchoolDataRecord | null {
  const slug = toCollegeSlug(college.name);
  const source = TEST_OVERRIDE ?? SCHOOL_DATA;
  const byPlan = source[slug];
  if (!byPlan) return null;
  return byPlan[plan] ?? null;
}

// ── Math helpers ────────────────────────────────────────────────────────────
function clamp(x: number, lo: number, hi: number): number {
  return Math.min(hi, Math.max(lo, x));
}

// Approximation of the standard normal CDF (Abramowitz & Stegun 26.2.17).
// Avoids pulling in a stats library for one call.
function normalCdf(z: number): number {
  const t = 1 / (1 + 0.2316419 * Math.abs(z));
  const d = 0.3989422804 * Math.exp(-(z * z) / 2);
  const p =
    d *
    t *
    (0.31938153 +
      t *
        (-0.356563782 +
          t * (1.781477937 + t * (-1.821255978 + t * 1.330274429))));
  return z < 0 ? p : 1 - p;
}

/**
 * S-curve mapping percentile (0-1) to multiplier on schoolAdmitRate.
 *
 * Anchors (rule-of-thumb, no published source):
 *   0.0 → 0.3x  (well below the admitted distribution)
 *   0.5 → 1.0x  (median admitted)
 *   0.9 → 2.5x  (top decile of admits)
 * Smoothly extrapolates outside [0, 1] via the underlying logistic.
 */
function percentileMultiplier(p: number): number {
  // logistic 0.3 → 2.5 over p in [0, 0.9]; tuned by hand to hit anchors.
  const t = clamp(p, 0, 1);
  // map t through logistic centered at 0.5 with steepness ~5.
  const x = 5 * (t - 0.5);
  const sig = 1 / (1 + Math.exp(-x));
  // sig(0) = 0.5 → maps to ~1.0x; sig(2.5) ≈ 0.924 → ~2.5x; sig(-2.5) ≈ 0.076 → ~0.3x.
  return 0.3 + sig * (2.5 - 0.3);
}

/**
 * Estimate the user's percentile within the admitted distribution at this
 * school. Uses SAT primarily (stronger normalization than weighted GPA which
 * varies by HS scale). Falls back to GPA when no SAT is available.
 *
 * Returns null when there isn't enough data to ground a percentile.
 */
function userPercentileWithinAdmits(
  user: { gpaWeighted: number | null; sat: number | null },
  record: SchoolDataRecord,
): number | null {
  if (
    user.sat != null &&
    record.admittedAvgSAT != null &&
    record.admittedStdSAT != null &&
    record.admittedStdSAT > 0
  ) {
    const z = (user.sat - record.admittedAvgSAT) / record.admittedStdSAT;
    return normalCdf(z);
  }
  if (
    user.gpaWeighted != null &&
    record.admittedAvgGPA != null &&
    record.admittedStdGPA != null &&
    record.admittedStdGPA > 0
  ) {
    const z = (user.gpaWeighted - record.admittedAvgGPA) / record.admittedStdGPA;
    return normalCdf(z);
  }
  return null;
}

// ── Blend ───────────────────────────────────────────────────────────────────
export interface SchoolBlendResult {
  readonly applied: boolean;
  /** Final blended chance, percent (0-100). Equals nationalChance when not applied. */
  readonly mid: number;
  /** National model output (passed through, percent). */
  readonly nationalChance: number;
  /** School-derived chance (percent). null when not computable. */
  readonly schoolChance: number | null;
  /** Blend weight on the school side. 0 when not applied. */
  readonly schoolWeight: number;
  /** Sample-size confidence label propagated from the importer. null when not applied. */
  readonly sampleSizeLabel: "limited" | "moderate" | "strong" | null;
  /** Inline note appended to the chance reason when shift >5pp. */
  readonly callout: string | null;
  /** The matching record, for downstream surfaces (scatterplot, breakdown). */
  readonly record: SchoolDataRecord | null;
}

const NO_BLEND: Omit<SchoolBlendResult, "mid" | "nationalChance"> = {
  applied: false,
  schoolChance: null,
  schoolWeight: 0,
  sampleSizeLabel: null,
  callout: null,
  record: null,
};

export function applySchoolHistory(
  nationalChance: number,                  // 0-100
  college: College,
  plan: ApplicationPlan,
  user: { gpaWeighted: number | null; sat: number | null },
): SchoolBlendResult {
  const record = getSchoolRecord(college, plan);
  if (!record) {
    return { ...NO_BLEND, mid: nationalChance, nationalChance };
  }
  if (record.totalApplicants < 5) {
    // Sample too small — surface the existence of the data but don't shift.
    return {
      ...NO_BLEND,
      mid: nationalChance,
      nationalChance,
      record,
      sampleSizeLabel: record.sampleSizeLabel,
      callout:
        `Your high school has limited history at this college ` +
        `(${record.totalApplicants} applicants) — national estimate used.`,
    };
  }

  const pct = userPercentileWithinAdmits(user, record);
  // Without a percentile we still adjust toward the school's raw admit rate,
  // but with a moderate weight only. Otherwise schoolChance == raw admit rate.
  const mult = pct == null ? 1.0 : percentileMultiplier(pct);
  const schoolChancePct = clamp(record.schoolAdmitRate * 100 * mult, 0.5, 95);

  const schoolWeight = Math.min(0.5, record.totalApplicants / 30);
  const blended = (1 - schoolWeight) * nationalChance + schoolWeight * schoolChancePct;
  const finalMid = clamp(blended, 0.5, 95);

  const shift = finalMid - nationalChance;
  // Always surface the school sample fact when the blend applies. Use a
  // directional verb when the shift is meaningful (>=0.5pp), otherwise just
  // state the record. This way users always know when their HS history was
  // factored in, even on small shifts.
  let callout: string;
  if (shift > 0.5) {
    callout =
      `Your high school's history at this college shifts the estimate up ` +
      `(${record.totalAdmits}/${record.totalApplicants} admitted).`;
  } else if (shift < -0.5) {
    callout =
      `Your high school's history at this college shifts the estimate down ` +
      `(${record.totalAdmits}/${record.totalApplicants} admitted).`;
  } else {
    callout =
      `Your high school's record at this college: ` +
      `${record.totalAdmits}/${record.totalApplicants} admitted.`;
  }

  return {
    applied: true,
    mid: finalMid,
    nationalChance,
    schoolChance: schoolChancePct,
    schoolWeight,
    sampleSizeLabel: record.sampleSizeLabel,
    callout,
    record,
  };
}
