"use client";

/**
 * SchoolHistoryScatterplot
 *
 * Renders feeder-school applications to one college as a scatter plot.
 * GPA on x, score on y. ACT-only points are concorded to their SAT equivalent
 * using the College Board / ACT concordance table so everything fits on a
 * single axis. Color = outcome. The user's own stats render as a labeled
 * diamond. Click any point to inspect its full anonymized stat line below.
 *
 * Data: src/data/school-specific-data.json (generated by import-school-data.ts).
 */
import { useEffect, useMemo, useState } from "react";
import {
  CartesianGrid,
  ResponsiveContainer,
  Scatter,
  ScatterChart,
  Tooltip,
  XAxis,
  YAxis,
  ZAxis,
} from "recharts";
import type { ApplicationPlan, College } from "@/lib/college-types";
import { getSchoolRecord, type SchoolDataRecord } from "@/lib/school-data";

// ── ACT → SAT concordance ────────────────────────────────────────────────────
// Source: College Board / ACT concordance (2018 update). Used to put ACT-only
// points on the same y-axis as SAT-scored points so the chart shows ONE
// distribution, not two. Values are ACT composite → SAT total midpoint.
const ACT_TO_SAT: Record<number, number> = {
  36: 1590, 35: 1540, 34: 1500, 33: 1460, 32: 1430, 31: 1400, 30: 1370,
  29: 1340, 28: 1310, 27: 1280, 26: 1240, 25: 1210, 24: 1180, 23: 1140,
  22: 1110, 21: 1080, 20: 1040, 19: 1010, 18: 970, 17: 930, 16: 890,
  15: 850, 14: 800, 13: 760, 12: 710, 11: 670, 10: 630, 9: 590,
};

function actToSat(act: number): number | null {
  const rounded = Math.max(9, Math.min(36, Math.round(act)));
  return ACT_TO_SAT[rounded] ?? null;
}

function unifiedScore(sat: number | null, act: number | null): number | null {
  if (sat != null) return sat;
  if (act != null) return actToSat(act);
  return null;
}

// ── Types ───────────────────────────────────────────────────────────────────
interface UserStats {
  readonly gpaWeighted: number | null;
  readonly gpaUnweighted?: number | null;
  readonly sat: number | null;
  readonly act: number | null;
}

interface Props {
  readonly college: College;
  readonly userStats: UserStats;
  readonly defaultAppType?: string;
}

interface PlotPoint {
  readonly id: string;
  readonly gpa: number;
  readonly score: number;             // SAT or SAT-equivalent (ACT concorded)
  readonly satOriginal: number | null;
  readonly actOriginal: number | null;
  readonly outcome: "Accepted" | "Denied" | "Waitlisted";
  readonly classYear: number;
  readonly isUser: boolean;
}

const OUTCOME: Record<PlotPoint["outcome"], { color: string; label: string }> = {
  Accepted:   { color: "oklch(74% 0.16 155)", label: "Admitted" },
  Denied:     { color: "oklch(64% 0.18 25)",  label: "Denied" },
  Waitlisted: { color: "oklch(78% 0.14 80)",  label: "Waitlisted" },
};
const USER_COLOR = "oklch(72% 0.16 240)"; // tinted toward zinc/blue

// ── Lookup helpers ──────────────────────────────────────────────────────────
function recordsByPlan(college: College): readonly { plan: string; record: SchoolDataRecord }[] {
  const out: { plan: string; record: SchoolDataRecord }[] = [];
  const opts: ApplicationPlan[] = ["ED", "ED2", "EA", "REA", "SCEA", "RD", "Rolling"];
  for (const plan of opts) {
    const rec = getSchoolRecord(college, plan);
    if (rec) out.push({ plan, record: rec });
  }
  return out;
}

function recordToPoints(record: SchoolDataRecord): PlotPoint[] {
  const out: PlotPoint[] = [];
  record.rawDataPoints.forEach((p, i) => {
    const score = unifiedScore(p.sat, p.act);
    if (p.gpaWeighted == null || score == null) return;
    out.push({
      id: `pt-${i}`,
      gpa: p.gpaWeighted,
      score,
      satOriginal: p.sat,
      actOriginal: p.act,
      outcome: p.outcome,
      classYear: p.classYear,
      isUser: false,
    });
  });
  return out;
}

function userToPoint(user: UserStats): PlotPoint | null {
  const score = unifiedScore(user.sat, user.act);
  if (user.gpaWeighted == null || score == null) return null;
  return {
    id: "user",
    gpa: user.gpaWeighted,
    score,
    satOriginal: user.sat,
    actOriginal: user.act,
    outcome: "Accepted",
    classYear: 0,
    isUser: true,
  };
}

// ── Component ───────────────────────────────────────────────────────────────
export default function SchoolHistoryScatterplot({
  college,
  userStats,
  defaultAppType,
}: Props): React.ReactElement | null {
  const allRecords = recordsByPlan(college);
  const initialPlan =
    defaultAppType && allRecords.find((r) => r.plan === defaultAppType)
      ? defaultAppType
      : allRecords[0]?.plan ?? "RD";

  const [activePlan, setActivePlan] = useState<string>(initialPlan);
  const [selected, setSelected] = useState<PlotPoint | null>(null);

  useEffect(() => {
    // Reset selection when plan changes — selected point is stale.
    setSelected(null);
  }, [activePlan, college.name]);

  // Hooks must run unconditionally — defer the early return until after them.
  const active = allRecords.find((r) => r.plan === activePlan) ?? allRecords[0];
  const record = active?.record ?? null;

  const userPoint = useMemo(() => userToPoint(userStats), [userStats]);
  const points = useMemo(() => (record ? recordToPoints(record) : []), [record]);

  const buckets = useMemo(() => {
    const b: Record<PlotPoint["outcome"], PlotPoint[]> = {
      Accepted: [], Denied: [], Waitlisted: [],
    };
    for (const p of points) b[p.outcome].push(p);
    return b;
  }, [points]);

  if (allRecords.length === 0 || !record) return null;

  const yearsCovered = new Set(points.map((p) => p.classYear).filter((y) => y > 0)).size;
  const userSatEq = userPoint?.score;

  const handleSelect = (p: PlotPoint): void => {
    setSelected((cur) => (cur && cur.id === p.id ? null : p));
  };

  return (
    <section className="space-y-5">
      {/* Header — title + sample stats. No nested h3; this section is itself
          rendered inside an outer h-tag. Keep typography clean and editorial. */}
      <header className="flex flex-wrap items-baseline justify-between gap-3">
        <div className="space-y-1">
          <p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-zinc-500">
            Your high school’s record at {college.name}
          </p>
          <p className="text-[13px] text-zinc-400 leading-snug max-w-prose">
            <span className="text-zinc-100 font-mono tabular-nums">{record.totalAdmits}</span>
            <span className="text-zinc-500"> admitted of </span>
            <span className="text-zinc-100 font-mono tabular-nums">{record.totalApplicants}</span>
            <span className="text-zinc-500"> applicants{yearsCovered > 0 ? ` over ${yearsCovered} year${yearsCovered === 1 ? "" : "s"}` : ""}. ACT scores concorded to SAT-equivalent.</span>
          </p>
        </div>

        {/* Plan tabs — only render when more than one plan has data. */}
        {allRecords.length > 1 && (
          <div className="flex items-center gap-1 rounded-full bg-white/[0.04] p-1 ring-1 ring-white/[0.05]">
            {allRecords.map((r) => {
              const isActive = r.plan === activePlan;
              return (
                <button
                  key={r.plan}
                  type="button"
                  onClick={() => setActivePlan(r.plan)}
                  className={
                    "rounded-full px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.12em] transition-colors duration-200 " +
                    (isActive
                      ? "bg-zinc-100 text-zinc-900"
                      : "text-zinc-400 hover:text-zinc-200")
                  }
                >
                  <span>{r.plan}</span>
                  <span className="ml-1.5 font-mono text-[10px] tabular-nums opacity-70">
                    {r.record.totalApplicants}
                  </span>
                </button>
              );
            })}
          </div>
        )}
      </header>

      {/* Chart surface */}
      <div className="relative rounded-2xl bg-[#0b0b16]/70 ring-1 ring-white/[0.06] p-4 sm:p-5">
        <div className="h-[340px] sm:h-[380px] w-full">
          <ResponsiveContainer width="100%" height="100%">
            <ScatterChart margin={{ top: 12, right: 16, bottom: 28, left: 16 }}>
              <CartesianGrid stroke="rgba(255,255,255,0.05)" strokeDasharray="2 4" />
              <XAxis
                type="number"
                dataKey="gpa"
                domain={[3.5, 5.0]}
                ticks={[3.6, 3.8, 4.0, 4.2, 4.4, 4.6, 4.8, 5.0]}
                tickFormatter={(v: number) => v.toFixed(1)}
                tick={{ fill: "#a1a1aa", fontSize: 11, fontFamily: "ui-monospace,monospace" }}
                stroke="rgba(255,255,255,0.12)"
                axisLine={{ stroke: "rgba(255,255,255,0.12)" }}
                tickLine={false}
                label={{
                  // SVG text has no textTransform — pre-uppercase the literal.
                  value: "GPA (WEIGHTED)",
                  position: "insideBottom",
                  offset: -12,
                  fill: "#71717a",
                  fontSize: 10,
                  letterSpacing: "0.18em",
                }}
              />
              <YAxis
                type="number"
                dataKey="score"
                domain={[1100, 1600]}
                ticks={[1100, 1200, 1300, 1400, 1500, 1600]}
                tick={{ fill: "#a1a1aa", fontSize: 11, fontFamily: "ui-monospace,monospace" }}
                stroke="rgba(255,255,255,0.12)"
                axisLine={{ stroke: "rgba(255,255,255,0.12)" }}
                tickLine={false}
                width={48}
                label={{
                  value: "SAT (OR ACT-EQUIVALENT)",
                  angle: -90,
                  position: "insideLeft",
                  offset: 8,
                  fill: "#71717a",
                  fontSize: 10,
                  letterSpacing: "0.18em",
                  style: { textAnchor: "middle" },
                }}
              />
              <ZAxis range={[80, 80]} />
              <Tooltip
                cursor={false}
                wrapperStyle={{ outline: "none" }}
                content={<TooltipBody />}
              />
              <Scatter
                name="Admitted"
                data={buckets.Accepted}
                fill={OUTCOME.Accepted.color}
                fillOpacity={0.85}
                stroke="rgba(0,0,0,0.4)"
                strokeWidth={0.5}
                onClick={(d) => handleSelect(d as unknown as PlotPoint)}
                cursor="pointer"
              />
              <Scatter
                name="Denied"
                data={buckets.Denied}
                fill={OUTCOME.Denied.color}
                fillOpacity={0.7}
                stroke="rgba(0,0,0,0.4)"
                strokeWidth={0.5}
                onClick={(d) => handleSelect(d as unknown as PlotPoint)}
                cursor="pointer"
              />
              <Scatter
                name="Waitlisted"
                data={buckets.Waitlisted}
                fill={OUTCOME.Waitlisted.color}
                fillOpacity={0.85}
                stroke="rgba(0,0,0,0.4)"
                strokeWidth={0.5}
                onClick={(d) => handleSelect(d as unknown as PlotPoint)}
                cursor="pointer"
              />
              {userPoint && (
                <Scatter
                  name="You"
                  data={[userPoint]}
                  fill={USER_COLOR}
                  shape={renderUserMarker}
                  onClick={(d) => handleSelect(d as unknown as PlotPoint)}
                  cursor="pointer"
                />
              )}
            </ScatterChart>
          </ResponsiveContainer>
        </div>

        {/* Custom legend with intentional layout — replaces Recharts' default
            which wrapped awkwardly on narrow widths. */}
        <div className="mt-2 flex flex-wrap items-center gap-x-5 gap-y-2 text-[11px] text-zinc-400">
          <LegendDot color={OUTCOME.Accepted.color} label="Admitted" />
          <LegendDot color={OUTCOME.Denied.color} label="Denied" />
          <LegendDot color={OUTCOME.Waitlisted.color} label="Waitlisted" />
          {userPoint && <LegendDot color={USER_COLOR} label="You" diamond />}
        </div>
      </div>

      {/* Click-detail card. Stays mounted below the chart so the user keeps
          the spatial reference instead of having a popover obscure the data. */}
      <DetailCard
        point={selected}
        userScore={userSatEq ?? null}
        onClose={() => setSelected(null)}
      />
    </section>
  );
}

// ── Sub-components ──────────────────────────────────────────────────────────

interface MarkerProps {
  cx?: number;
  cy?: number;
  fill?: string;
}

function renderUserMarker({ cx, cy, fill }: MarkerProps): React.ReactElement {
  if (cx == null || cy == null) return <g />;
  // Diamond + halo so the user point is unmistakable against the cluster.
  return (
    <g>
      <circle cx={cx} cy={cy} r={14} fill={fill} fillOpacity={0.18} />
      <circle cx={cx} cy={cy} r={9} fill={fill} fillOpacity={0.32} />
      <polygon
        points={`${cx},${cy - 6} ${cx + 6},${cy} ${cx},${cy + 6} ${cx - 6},${cy}`}
        fill={fill}
        stroke="rgba(255,255,255,0.6)"
        strokeWidth={1.2}
      />
    </g>
  );
}

interface TooltipDatum { payload?: PlotPoint; }
interface TooltipProps { active?: boolean; payload?: TooltipDatum[]; }

function TooltipBody({ active, payload }: TooltipProps): React.ReactElement | null {
  if (!active || !payload || payload.length === 0) return null;
  const d = payload[0]?.payload;
  if (!d) return null;
  const oc = OUTCOME[d.outcome];
  return (
    <div className="rounded-lg border border-white/10 bg-[#0a0a14]/95 px-3 py-2 text-[11px] backdrop-blur-md shadow-xl">
      <div className="flex items-center gap-2 mb-1">
        <span
          className="inline-block h-2 w-2 rounded-full"
          style={{ background: d.isUser ? USER_COLOR : oc.color }}
        />
        <span className="font-semibold text-zinc-100">
          {d.isUser ? "You" : `Class of ${d.classYear}`}
        </span>
      </div>
      <div className="font-mono tabular-nums text-zinc-300">
        GPA {d.gpa.toFixed(2)} · SAT {d.score}
        {d.actOriginal != null && d.satOriginal == null ? ` (ACT ${d.actOriginal})` : ""}
      </div>
      {!d.isUser && (
        <div className="mt-0.5 text-[10px] uppercase tracking-[0.12em]" style={{ color: oc.color }}>
          {oc.label}
        </div>
      )}
      <div className="mt-1.5 text-[10px] text-zinc-500">Click for full stats</div>
    </div>
  );
}

function LegendDot({
  color,
  label,
  diamond,
}: {
  color: string;
  label: string;
  diamond?: boolean;
}): React.ReactElement {
  return (
    <span className="inline-flex items-center gap-1.5">
      {diamond ? (
        <span
          aria-hidden
          className="inline-block h-2.5 w-2.5"
          style={{ background: color, transform: "rotate(45deg)" }}
        />
      ) : (
        <span
          aria-hidden
          className="inline-block h-2 w-2 rounded-full"
          style={{ background: color }}
        />
      )}
      <span>{label}</span>
    </span>
  );
}

interface DetailCardProps {
  point: PlotPoint | null;
  userScore: number | null;
  onClose: () => void;
}

function DetailCard({ point, userScore, onClose }: DetailCardProps): React.ReactElement | null {
  if (!point) return null;
  const oc = OUTCOME[point.outcome];
  const swatch = point.isUser ? USER_COLOR : oc.color;

  // Plain-language comparison line. Drops the cryptic "Δ vs you / -88 SAT-eq"
  // labeled stat in favor of a sentence the user can read at a glance.
  let comparison: { phrase: string; tone: "neutral" | "above" | "below" } | null = null;
  if (!point.isUser && userScore != null) {
    const diff = point.score - userScore;
    const abs = Math.abs(diff);
    if (abs <= 10) {
      comparison = { phrase: "Same score range as yours", tone: "neutral" };
    } else if (diff > 0) {
      comparison = {
        phrase: `Scored ${abs} SAT points above you`,
        tone: "above",
      };
    } else {
      comparison = {
        phrase: `Scored ${abs} SAT points below you`,
        tone: "below",
      };
    }
  }

  return (
    <div className="relative rounded-2xl bg-[#0b0b16]/70 ring-1 ring-white/[0.06] px-5 py-4">
      <button
        type="button"
        onClick={onClose}
        aria-label="Dismiss"
        className="absolute right-3 top-3 text-zinc-500 hover:text-zinc-200 text-[18px] leading-none"
      >
        ×
      </button>

      <div className="flex flex-wrap items-baseline gap-x-4 gap-y-1.5 mb-3">
        <span
          aria-hidden
          className="inline-block h-2.5 w-2.5 rounded-full mt-1"
          style={{ background: swatch }}
        />
        <h4 className="text-[13px] font-semibold tracking-tight text-zinc-100">
          {point.isUser ? "Your profile" : `Anonymous applicant · Class of ${point.classYear}`}
        </h4>
        {!point.isUser && (
          <span
            className="text-[10px] font-semibold uppercase tracking-[0.14em]"
            style={{ color: oc.color }}
          >
            {oc.label}
          </span>
        )}
      </div>

      {comparison && (
        <p className="mb-3 text-[12px] leading-snug text-zinc-300">
          {comparison.phrase}
          {comparison.tone === "neutral" ? "." : "."}
        </p>
      )}

      <dl className="grid grid-cols-3 gap-x-6 gap-y-3 text-[12px]">
        <Stat label="GPA (weighted)" value={point.gpa.toFixed(2)} />
        <Stat
          label="SAT"
          value={point.satOriginal != null ? `${point.satOriginal}` : "—"}
          subtext={point.satOriginal == null ? `${point.score} (from ACT)` : undefined}
        />
        <Stat
          label="ACT"
          value={point.actOriginal != null ? `${point.actOriginal}` : "—"}
        />
      </dl>
    </div>
  );
}

function Stat({
  label,
  value,
  subtext,
}: {
  label: string;
  value: string;
  subtext?: string;
}): React.ReactElement {
  return (
    <div className="space-y-0.5">
      <dt className="text-[10px] font-semibold uppercase tracking-[0.14em] text-zinc-500">
        {label}
      </dt>
      <dd className="font-mono tabular-nums text-zinc-100">{value}</dd>
      {subtext && (
        <dd className="text-[10px] font-mono tabular-nums text-zinc-500">{subtext}</dd>
      )}
    </div>
  );
}
