"use client";

/**
 * SchoolHistoryScatterplot
 *
 * Sandbox component. Renders a Recharts ScatterChart of every imported
 * application from the user's HS to one college, colored by outcome, with
 * the user's stats overlaid as a labeled diamond.
 *
 * Data source: src/data/school-specific-data.json (generated by
 * scripts/import-school-data.ts).
 */
import { useEffect, useState } from "react";
import {
  ResponsiveContainer,
  ScatterChart,
  Scatter,
  XAxis,
  YAxis,
  ZAxis,
  Tooltip,
  Legend,
  CartesianGrid,
} from "recharts";
import type { College, ApplicationPlan } from "@/lib/college-types";
import { getSchoolRecord, type SchoolDataRecord } from "@/lib/school-data";

const Y_AXIS_KEY = "school-scatter-y-axis";

type YAxisType = "sat" | "act";

interface UserStats {
  readonly gpaWeighted: number | null;
  readonly sat: number | null;
  readonly act: number | null;
}

interface Props {
  readonly college: College;
  readonly userStats: UserStats;
  readonly defaultAppType?: string;
}

interface PlotPoint {
  readonly gpa: number;
  readonly y: number; // SAT or ACT
  readonly outcome: "Accepted" | "Denied" | "Waitlisted";
  readonly classYear: number;
}

const OUTCOME_COLORS: Record<PlotPoint["outcome"], string> = {
  // Tailwind-ish swatches; matches conventions in DemographicsChart.tsx.
  Accepted: "#22c55e",   // green-500
  Denied: "#ef4444",     // red-500
  Waitlisted: "#eab308", // yellow-500
};

function recordsByPlan(college: College): readonly { plan: string; record: SchoolDataRecord }[] {
  const out: { plan: string; record: SchoolDataRecord }[] = [];
  // We only know the plans in advance via opts; iterate them and try lookup.
  const opts: ApplicationPlan[] = ["ED", "ED2", "EA", "REA", "SCEA", "RD", "Rolling"];
  for (const plan of opts) {
    const rec = getSchoolRecord(college, plan);
    if (rec) out.push({ plan, record: rec });
  }
  return out;
}

export default function SchoolHistoryScatterplot({
  college,
  userStats,
  defaultAppType,
}: Props): React.ReactElement | null {
  const allRecords = recordsByPlan(college);
  const initialPlan =
    defaultAppType && allRecords.find((r) => r.plan === defaultAppType)
      ? defaultAppType
      : allRecords[0]?.plan ?? "RD";

  const [activePlan, setActivePlan] = useState<string>(initialPlan);
  const [yAxis, setYAxis] = useState<YAxisType>("sat");

  useEffect(() => {
    if (typeof window === "undefined") return;
    const saved = window.localStorage.getItem(Y_AXIS_KEY);
    if (saved === "sat" || saved === "act") setYAxis(saved);
  }, []);

  const setYAxisPersisted = (val: YAxisType): void => {
    setYAxis(val);
    if (typeof window !== "undefined") {
      window.localStorage.setItem(Y_AXIS_KEY, val);
    }
  };

  if (allRecords.length === 0) return null;
  const active = allRecords.find((r) => r.plan === activePlan) ?? allRecords[0]!;
  const record = active.record;

  // Filter raw points to those with both GPA and the active y-axis populated.
  const points: PlotPoint[] = record.rawDataPoints
    .filter((p) => p.gpaWeighted != null && (yAxis === "sat" ? p.sat != null : p.act != null))
    .map((p) => ({
      gpa: p.gpaWeighted!,
      y: yAxis === "sat" ? p.sat! : p.act!,
      outcome: p.outcome,
      classYear: p.classYear,
    }));

  const buckets: Record<PlotPoint["outcome"], PlotPoint[]> = {
    Accepted: [],
    Denied: [],
    Waitlisted: [],
  };
  for (const p of points) buckets[p.outcome].push(p);

  // User point — only render when both axes are available.
  const userY = yAxis === "sat" ? userStats.sat : userStats.act;
  const showUser = userStats.gpaWeighted != null && userY != null;
  const userPoint = showUser
    ? [{ gpa: userStats.gpaWeighted!, y: userY!, outcome: "Accepted" as const, classYear: 0 }]
    : [];

  const sampleNote =
    `Based on ${record.totalApplicants} applicants from your high school over the last ${
      uniqueYears(record.rawDataPoints)
    } years (${record.totalAdmits} admitted).`;

  return (
    <div className="space-y-3">
      <div className="flex flex-wrap items-center gap-2 text-xs">
        <div className="flex gap-1">
          {allRecords.map((r) => (
            <button
              key={r.plan}
              type="button"
              onClick={() => setActivePlan(r.plan)}
              className={`rounded px-2 py-1 font-medium ${
                r.plan === activePlan
                  ? "bg-slate-900 text-white"
                  : "bg-slate-100 text-slate-700 hover:bg-slate-200"
              }`}
            >
              {r.plan} ({r.record.totalApplicants})
            </button>
          ))}
        </div>
        <div className="ml-auto flex gap-1">
          <button
            type="button"
            onClick={() => setYAxisPersisted("sat")}
            className={`rounded px-2 py-1 font-medium ${
              yAxis === "sat" ? "bg-slate-900 text-white" : "bg-slate-100 text-slate-700 hover:bg-slate-200"
            }`}
          >
            SAT
          </button>
          <button
            type="button"
            onClick={() => setYAxisPersisted("act")}
            className={`rounded px-2 py-1 font-medium ${
              yAxis === "act" ? "bg-slate-900 text-white" : "bg-slate-100 text-slate-700 hover:bg-slate-200"
            }`}
          >
            ACT
          </button>
        </div>
      </div>

      <div className="h-72 w-full">
        <ResponsiveContainer width="100%" height="100%">
          <ScatterChart margin={{ top: 12, right: 16, bottom: 36, left: 36 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
            <XAxis
              type="number"
              dataKey="gpa"
              name="GPA (weighted)"
              domain={["dataMin - 0.1", "dataMax + 0.1"]}
              tickFormatter={(v) => v.toFixed(1)}
              label={{ value: "GPA (weighted)", position: "insideBottom", offset: -10 }}
            />
            <YAxis
              type="number"
              dataKey="y"
              name={yAxis === "sat" ? "SAT" : "ACT"}
              domain={yAxis === "sat" ? [1100, 1600] : [18, 36]}
              label={{
                value: yAxis === "sat" ? "SAT" : "ACT",
                angle: -90,
                position: "insideLeft",
                offset: 10,
              }}
            />
            <ZAxis range={[60, 60]} />
            <Tooltip cursor={{ strokeDasharray: "3 3" }} content={<CustomTooltip />} />
            <Legend />
            <Scatter name="Accepted" data={buckets.Accepted} fill={OUTCOME_COLORS.Accepted} />
            <Scatter name="Denied" data={buckets.Denied} fill={OUTCOME_COLORS.Denied} />
            <Scatter name="Waitlisted" data={buckets.Waitlisted} fill={OUTCOME_COLORS.Waitlisted} />
            {userPoint.length > 0 && (
              <Scatter
                name="You"
                data={userPoint}
                fill="#2563eb"
                shape="diamond"
                legendType="diamond"
              />
            )}
          </ScatterChart>
        </ResponsiveContainer>
      </div>

      <p className="text-xs text-slate-500">{sampleNote}</p>
    </div>
  );
}

interface TooltipDatum {
  payload?: PlotPoint;
}
interface TooltipProps {
  active?: boolean;
  payload?: TooltipDatum[];
}

function CustomTooltip({ active, payload }: TooltipProps): React.ReactElement | null {
  if (!active || !payload || payload.length === 0) return null;
  const d = payload[0]?.payload;
  if (!d) return null;
  return (
    <div className="rounded border border-slate-200 bg-white px-2 py-1 text-xs shadow">
      <div className="font-semibold">{d.classYear === 0 ? "You" : `Class of ${d.classYear}`}</div>
      <div>GPA {d.gpa.toFixed(2)} · {d.y}</div>
      <div className="text-slate-500">{d.outcome}</div>
    </div>
  );
}

function uniqueYears(points: readonly { classYear: number }[]): number {
  return new Set(points.map((p) => p.classYear).filter((y) => y > 0)).size;
}
