// AUTO-GENERATED by scripts/cds-sync.ts — DO NOT EDIT BY HAND.
// Re-run: npm run sync:cds
//
// Authoritative stats pulled from each college's Common Data Set PDF.
// Merged into the College layer chain by src/data/colleges.ts so these
// values OVERRIDE the hand-curated estimates in colleges.ts and
// college-extended.ts at runtime, without modifying those files.

import type { College } from "@/lib/college-types";

export interface CDSEntry {
  readonly cdsYear: string;
  readonly sourcePdfUrl: string;
  readonly data: Partial<College>;
}

export const CDS_DATA: Record<string, CDSEntry> = {
  "Arizona State University": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://uoia.asu.edu/sites/g/files/litvpz1436/files/2026-04/CDS%202025-26%20-%20ASU%20Campus%20Immersion.pdf",
    data: {"acceptanceRate":88.4,"yield":22.2,"avgGPACDS":3.52,"top10HSPercent":29.9,"pctTopTenClass":29.9,"studentFacultyRatio":17.7,"fourYearGradRate":55.3,"undergradPopulation":64662,"inStatePercent":74.3,"percentInternational":8.2,"demographics":{"white":38.6,"asian":9.3,"hispanic":27.8,"black":4.6,"multiracial":5.4,"international":8.2,"other":4.8},"genderBreakdown":{"male":48.8,"female":51.2}},
  },
  "Boston College": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://www.bc.edu/content/dam/bc1/offices/irp/ir/cds/Boston_College_CDS_2024-2025_Final.pdf",
    data: {"acceptanceRate":16.2,"sat25":1460,"sat75":1520,"act25":33,"act75":35,"yield":42.5,"edAdmitRate":33.4,"top10HSPercent":90,"pctTopTenClass":90,"studentFacultyRatio":10,"fourYearGradRate":86.4,"undergradPopulation":9654,"inStatePercent":24,"percentInternational":6.6,"demographics":{"white":57.6,"asian":11.4,"hispanic":12.5,"black":5,"multiracial":5.2,"international":6.6,"other":1.7},"genderBreakdown":{"male":47.2,"female":52.8}},
  },
  "Boston University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://www.bu.edu/asir/files/2026/04/CDS_2024_25-updated-sect-I.pdf",
    data: {"acceptanceRate":11.1,"sat25":1430,"sat75":1510,"act25":32,"act75":34,"yield":37.4,"edAdmitRate":28.2,"avgGPACDS":3.9,"top10HSPercent":92,"pctTopTenClass":92,"studentFacultyRatio":10,"fourYearGradRate":86.7,"undergradPopulation":18805,"inStatePercent":22,"percentInternational":20.9,"demographics":{"white":31.8,"asian":20.1,"hispanic":11.2,"black":5.8,"multiracial":4.6,"international":20.9,"other":5.6},"genderBreakdown":{"male":41.9,"female":56.4}},
  },
  "Brown University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://oir.brown.edu/sites/default/files/2020-04/CDS_2024_2025.pdf",
    data: {"acceptanceRate":5.4,"sat25":1510,"sat75":1560,"act25":34,"act75":35,"yield":65.2,"edAdmitRate":14.4,"top10HSPercent":89,"pctTopTenClass":89,"studentFacultyRatio":6,"fourYearGradRate":80.1,"undergradPopulation":7910,"inStatePercent":3,"percentInternational":13.5,"demographics":{"white":30.4,"asian":21.2,"hispanic":11.3,"black":7.5,"multiracial":7.4,"international":13.5,"other":8.6},"genderBreakdown":{"male":49.8,"female":50.2}},
  },
  "Caltech": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://iro.caltech.edu/documents/31491/Caltech_CDS_2024-2025_May_2025.pdf",
    data: {"acceptanceRate":2.6,"yield":61.2,"top10HSPercent":86.4,"pctTopTenClass":86.4,"studentFacultyRatio":3,"fourYearGradRate":77.1,"undergradPopulation":987,"inStatePercent":37,"percentInternational":14.1,"demographics":{"white":18.7,"asian":35.9,"hispanic":17.4,"black":4.7,"multiracial":8.9,"international":14.1,"other":0.3},"genderBreakdown":{"male":54.8,"female":45.2}},
  },
  "Claremont McKenna College": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://www.cmc.edu/sites/default/files/CDS_2025-26_0.pdf",
    data: {"acceptanceRate":9.4,"sat25":1480,"sat75":1540,"act25":33,"act75":35,"yield":51.1,"edAdmitRate":22.1,"regularDecisionAdmitRate":7.4,"top10HSPercent":64,"pctTopTenClass":64,"studentFacultyRatio":8,"fourYearGradRate":70.3,"undergradPopulation":1378,"inStatePercent":40.7,"percentInternational":13.7,"demographics":{"white":34.8,"asian":19.8,"hispanic":13.6,"black":3.6,"multiracial":9.6,"international":13.7,"other":5.1},"genderBreakdown":{"male":50.9,"female":49.1}},
  },
  "Colgate University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://www.colgate.edu/sites/default/files/2025-07/Colgate%202024-25%20CDS%20for%20Website_0.pdf",
    data: {"acceptanceRate":13.5,"sat25":1450,"sat75":1530,"act25":33,"act75":34,"yield":28.8,"edAdmitRate":19.5,"regularDecisionAdmitRate":11.2,"avgGPACDS":3.85,"top10HSPercent":79,"pctTopTenClass":79,"studentFacultyRatio":8.8,"fourYearGradRate":84.9,"undergradPopulation":3193,"inStatePercent":24,"percentInternational":8.1,"demographics":{"white":64.3,"asian":5.3,"hispanic":9.6,"black":4.3,"multiracial":6,"international":8.1,"other":2.3},"genderBreakdown":{"male":42.8,"female":55.9}},
  },
  "Columbia University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://opir.columbia.edu/sites/opir.columbia.edu/files/content/Common%20Data%20Set/2024-25_Columbia_College_and_Columbia_Engineering_CDS.pdf",
    data: {"acceptanceRate":3.9,"sat25":1510,"sat75":1560,"act25":34,"act75":36,"yield":63.8,"edAdmitRate":13.2,"regularDecisionAdmitRate":2.8,"top10HSPercent":94,"pctTopTenClass":94,"studentFacultyRatio":6,"fourYearGradRate":83.1,"undergradPopulation":6597,"inStatePercent":20,"percentInternational":16.3,"demographics":{"white":26.4,"asian":21.7,"hispanic":16.8,"black":8.1,"multiracial":7.1,"international":16.3,"other":0.5},"genderBreakdown":{"male":48.9,"female":49.4}},
  },
  "Cornell University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "http://irp.dpb.cornell.edu/wp-content/uploads/2025/07/CDS-2024-2025-v6-print.pdf",
    data: {"acceptanceRate":8.4,"sat25":1510,"sat75":1560,"act25":33,"act75":35,"yield":63.9,"edAdmitRate":11.6,"regularDecisionAdmitRate":7.8,"top10HSPercent":85.6,"pctTopTenClass":85.6,"studentFacultyRatio":9,"fourYearGradRate":87,"undergradPopulation":16128,"inStatePercent":35,"percentInternational":10.3,"demographics":{"white":30.8,"asian":26.5,"hispanic":13.1,"black":6.8,"multiracial":5.9,"international":10.3,"other":6.5},"genderBreakdown":{"male":46.8,"female":53.2}},
  },
  "Dartmouth College": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://www.dartmouth.edu/oir/pdfs/cds_2025-26.pdf",
    data: {"acceptanceRate":6,"sat25":1440,"sat75":1550,"act25":32,"act75":35,"yield":70.9,"edAdmitRate":21.6,"top10HSPercent":96,"pctTopTenClass":96,"studentFacultyRatio":7.9,"fourYearGradRate":78.5,"undergradPopulation":4715,"inStatePercent":3,"percentInternational":14.5,"demographics":{"white":43.8,"asian":12.5,"hispanic":9.2,"black":5.2,"multiracial":7.5,"international":14.5,"other":6.2},"genderBreakdown":{"male":51.8,"female":48.2}},
  },
  "Drexel University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "Drexel_university_CDS-2024-2025-publish.pdf",
    data: {"acceptanceRate":79.4,"yield":8.1,"edAdmitRate":91.7,"sat25":1250,"sat75":1430,"act25":27,"act75":32,"avgGPACDS":3.75,"top10HSPercent":27.5,"pctTopTenClass":27.5,"studentFacultyRatio":9.4,"undergradPopulation":13169,"inStatePercent":43.2,"percentInternational":9.1,"demographics":{"white":40.3,"asian":24.4,"hispanic":9.1,"black":10.1,"multiracial":4.6,"international":9.1,"other":2.3},"genderBreakdown":{"male":50.1,"female":47.8}},
  },
  "Duke University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://ir.provost.duke.edu/sites/default/files/CDS-2024-25-Final-2.pdf",
    data: {"acceptanceRate":5.7,"sat25":1500,"sat75":1570,"act25":34,"act75":35,"yield":58.8,"edAdmitRate":17.3,"top10HSPercent":92,"pctTopTenClass":92,"studentFacultyRatio":5,"fourYearGradRate":86.7,"undergradPopulation":6523,"inStatePercent":17,"percentInternational":10.6,"demographics":{"white":35,"asian":21.6,"hispanic":10.7,"black":8.6,"multiracial":7.3,"international":10.6,"other":6},"genderBreakdown":{"male":46.3,"female":53.7}},
  },
  "Emory University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://provost.emory.edu/planning-administration/_includes/documents/sections/institutional-data/emory-common-data-set-2024-2025.pdf",
    data: {"acceptanceRate":10.3,"sat25":1480,"sat75":1540,"act25":32,"act75":35,"yield":40.4,"edAdmitRate":23.2,"avgGPACDS":3.84,"top10HSPercent":80,"pctTopTenClass":80,"studentFacultyRatio":8,"fourYearGradRate":80.9,"undergradPopulation":7407,"inStatePercent":18,"percentInternational":16.7,"demographics":{"white":29.6,"asian":24.8,"hispanic":11.9,"black":10.3,"multiracial":4.1,"international":16.7,"other":2.5},"genderBreakdown":{"male":43.2,"female":56.8}},
  },
  "Florida International University": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "fiu_CDS2025.pdf",
    data: {"acceptanceRate":60.9,"yield":26.6,"sat25":1070,"sat75":1260,"act25":22,"act75":27,"top10HSPercent":23,"pctTopTenClass":23,"studentFacultyRatio":25,"fourYearGradRate":64,"undergradPopulation":46249,"inStatePercent":90.5,"percentInternational":7.7,"demographics":{"white":8.3,"asian":2.6,"hispanic":67.5,"black":11,"multiracial":2,"international":7.7,"other":1},"genderBreakdown":{"male":45.5,"female":54.5}},
  },
  "Florida State University": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "CDS.pdf (FSU section)",
    data: {"acceptanceRate":23.8,"yield":32.2,"sat25":1300,"sat75":1410,"act25":29,"act75":32,"avgGPACDS":3.72,"top10HSPercent":77.8,"pctTopTenClass":77.8,"studentFacultyRatio":17.1,"fourYearGradRate":74.9,"undergradPopulation":34271,"inStatePercent":86.8,"percentInternational":2.6,"demographics":{"white":55.8,"asian":4.1,"hispanic":24.2,"black":6.9,"multiracial":4.7,"international":2.6,"other":1.7},"genderBreakdown":{"male":44,"female":56}},
  },
  "George Washington University": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://irp.gwu.edu/sites/g/files/zaxdzs6056/files/2026-04/CDS-PDF-2025-2026.pdf",
    data: {"acceptanceRate":47.1,"sat25":1310,"sat75":1450,"act25":31,"act75":34,"yield":18.9,"top10HSPercent":44.1,"pctTopTenClass":44.1,"studentFacultyRatio":13,"fourYearGradRate":82.5,"undergradPopulation":11495,"inStatePercent":2.6,"percentInternational":8.4,"demographics":{"white":44.1,"asian":16.2,"hispanic":14.6,"black":8.6,"multiracial":5.9,"international":8.4,"other":2.2},"genderBreakdown":{"male":36.7,"female":63.3}},
  },
  "Georgia Tech": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "georgia_tech_CDS_2025-2026.pdf",
    data: {"acceptanceRate":13.3,"oosAcceptanceRate":10.1,"inStateAcceptanceRate":29.5,"yield":45.6,"sat25":1370,"sat75":1530,"act25":31,"act75":35,"avgGPACDS":4.17,"top10HSPercent":88.7,"pctTopTenClass":88.7,"studentFacultyRatio":20,"fourYearGradRate":65.5,"undergradPopulation":21028,"inStatePercent":59.5,"percentInternational":7.6,"demographics":{"white":32.1,"asian":37.1,"hispanic":8.7,"black":8.2,"multiracial":5.1,"international":7.6,"other":1.3},"genderBreakdown":{"male":60.2,"female":39.8}},
  },
  "Harvard University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://bpb-us-e1.wpmucdn.com/sites.harvard.edu/dist/6/210/files/2025/06/HarvardUniversity_CDS_2024-2025.pdf",
    data: {"acceptanceRate":3.6,"act25":34,"act75":36,"yield":83.6,"avgGPACDS":4.21,"top10HSPercent":94,"pctTopTenClass":94,"studentFacultyRatio":7,"undergradPopulation":7038,"inStatePercent":15,"percentInternational":15.7,"demographics":{"white":29.7,"asian":23.5,"hispanic":11.5,"black":8.9,"multiracial":7.7,"international":15.7,"other":2.8},"genderBreakdown":{"male":46.5,"female":53.5}},
  },
  "Harvey Mudd College": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://www.hmc.edu/institutional-research/wp-content/uploads/sites/42/2026/03/CDS-HMC-2025.2026_shared.pdf",
    data: {"acceptanceRate":12.3,"sat25":1500,"sat75":1560,"act25":35,"act75":36,"yield":36.7,"edAdmitRate":18.4,"top10HSPercent":95,"pctTopTenClass":95,"studentFacultyRatio":8,"fourYearGradRate":82.6,"undergradPopulation":913,"inStatePercent":50,"percentInternational":10.8,"demographics":{"white":25.5,"asian":21.7,"hispanic":20.4,"black":3.5,"multiracial":11.2,"international":10.8,"other":0.3},"genderBreakdown":{"male":48.8,"female":50.9}},
  },
  "Howard University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://ira.howard.edu/sites/ira.howard.edu/files/2025-06/Howard%20University%20-%20CDS%20PDF%20Format.pdf",
    data: {"acceptanceRate":41.3,"sat25":1050,"sat75":1250,"act25":22,"act75":28,"yield":19.4,"edAdmitRate":49.4,"avgGPACDS":3.75,"studentFacultyRatio":13,"fourYearGradRate":59.5,"undergradPopulation":11519,"inStatePercent":4.9,"percentInternational":3.9,"demographics":{"white":0.2,"asian":1.3,"hispanic":6,"black":67.4,"multiracial":4.7,"international":3.9,"other":16.4},"genderBreakdown":{"male":28.3,"female":71.7}},
  },
  "Johns Hopkins University": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://oira.jhu.edu/common-data-set-2025-26/",
    data: {"acceptanceRate":6.1,"yield":44.9,"edAdmitRate":10.9,"sat25":1530,"sat75":1565,"act25":35,"act75":35,"avgGPACDS":3.93,"top10HSPercent":100,"pctTopTenClass":100,"studentFacultyRatio":9,"fourYearGradRate":85.4,"undergradPopulation":6354,"inStatePercent":8.1,"percentInternational":14.4,"demographics":{"white":19.9,"asian":34,"hispanic":16.3,"black":7.2,"multiracial":5.9,"international":14.4,"other":2.3},"genderBreakdown":{"male":43.8,"female":55.1}},
  },
  "Lehigh University": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://data.lehigh.edu/sites/data.lehigh.edu/files/4.6.2026_CDS_Finalized-Published_Definition%20Sheet%20Removed%20for%20Website%20Posting_0.pdf",
    data: {"acceptanceRate":28.9,"sat25":1380,"sat75":1480,"act25":31,"act75":34,"yield":27.4,"edAdmitRate":47.4,"top10HSPercent":60,"pctTopTenClass":60,"studentFacultyRatio":11,"fourYearGradRate":75.7,"undergradPopulation":5986,"inStatePercent":26.3,"percentInternational":6.2,"demographics":{"white":59.9,"asian":10.9,"hispanic":11.6,"black":4.2,"multiracial":4.6,"international":6.2,"other":2.5},"genderBreakdown":{"male":51.1,"female":48.9}},
  },
  "MIT": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "CDS.pdf (MIT section)",
    data: {"acceptanceRate":4.5,"yield":86.1,"sat25":1520,"sat75":1570,"act25":34,"act75":36,"top10HSPercent":96,"pctTopTenClass":96,"studentFacultyRatio":3,"fourYearGradRate":82.7,"undergradPopulation":4535,"percentInternational":11.7,"demographics":{"white":21.3,"asian":35.2,"hispanic":14.1,"black":7.7,"multiracial":6.8,"international":11.7,"other":3.3},"genderBreakdown":{"male":51.8,"female":48.2}},
  },
  "Marquette University": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://www.marquette.edu/academic-effectiveness/institutional-research-analysis/documents/cds-2025-2026_final.pdf",
    data: {"acceptanceRate":78,"sat25":1230,"sat75":1360,"act25":26,"act75":30,"yield":12.3,"avgGPACDS":3.6,"top10HSPercent":28,"pctTopTenClass":28,"studentFacultyRatio":14,"fourYearGradRate":68,"undergradPopulation":8206,"inStatePercent":38,"percentInternational":1.3,"demographics":{"white":66,"asian":6.3,"hispanic":16,"black":5.5,"multiracial":3.5,"international":1.3,"other":1.2},"genderBreakdown":{"male":43.1,"female":56.9}},
  },
  "Michigan State University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://xmc-michiganstab57e-msustrategi129d-prod9868.sitecorecloud.io/-/media/project/msu/ir/docs/cds/cds-2024-2025.pdf",
    data: {"acceptanceRate":84.8,"sat25":1100,"sat75":1310,"act25":24,"act75":30,"yield":18.3,"avgGPACDS":3.74,"top10HSPercent":23.1,"pctTopTenClass":23.1,"studentFacultyRatio":16.9,"fourYearGradRate":62.7,"undergradPopulation":41234,"inStatePercent":83.5,"percentInternational":5,"demographics":{"white":67.2,"asian":7.9,"hispanic":6.7,"black":6.6,"multiracial":4.4,"international":5,"other":2.1},"genderBreakdown":{"male":47.3,"female":52.7}},
  },
  "NYU": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://www.nyu.edu/content/dam/nyu/institutionalResearch/documents/cds-2024-2025/CDS_2024-2025-1.pdf",
    data: {"acceptanceRate":9.2,"sat25":1480,"sat75":1550,"act25":34,"act75":35,"yield":55,"avgGPACDS":3.81,"studentFacultyRatio":8,"fourYearGradRate":73.7,"undergradPopulation":29060,"inStatePercent":34,"percentInternational":26.2,"demographics":{"white":22,"asian":22,"hispanic":14.3,"black":6.8,"multiracial":4.3,"international":26.2,"other":4},"genderBreakdown":{"male":40.7,"female":59.3}},
  },
  "New Jersey Institute of Technology": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "njit_CDS_2024-2025_v12.xlsx",
    data: {"acceptanceRate":65.1,"yield":17.2,"sat25":1235,"sat75":1460,"act25":28,"act75":31,"avgGPACDS":3.73,"top10HSPercent":30.2,"pctTopTenClass":30.2,"studentFacultyRatio":16,"fourYearGradRate":48.8,"undergradPopulation":10200,"inStatePercent":85.3,"percentInternational":5.9,"demographics":{"white":28.4,"asian":19.5,"hispanic":27.2,"black":11.4,"multiracial":2.9,"international":5.9,"other":4.6},"genderBreakdown":{"male":69.4,"female":30.6}},
  },
  "North Carolina State University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://report.isa.ncsu.edu/ir/cds/pdfs/CDS_2024-25.v3.pdf",
    data: {"acceptanceRate":41.3,"sat25":1290,"sat75":1440,"act25":25,"act75":32,"yield":29.7,"avgGPACDS":3.83,"top10HSPercent":40,"pctTopTenClass":40,"studentFacultyRatio":15,"fourYearGradRate":67.7,"undergradPopulation":28422,"inStatePercent":86,"percentInternational":2.3,"demographics":{"white":66.1,"asian":9.8,"hispanic":9.4,"black":5.9,"multiracial":5.1,"international":2.3,"other":1.3},"genderBreakdown":{"male":50,"female":50}},
  },
  "Northeastern University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "http://uds.northeastern.edu/wp-content/uploads/2026/03/CDS-2024-25.pdf",
    data: {"acceptanceRate":5.2,"sat25":1450,"sat75":1520,"act25":33,"act75":35,"yield":53.8,"edAdmitRate":43,"top10HSPercent":68.8,"pctTopTenClass":68.8,"studentFacultyRatio":16,"undergradPopulation":22695,"inStatePercent":29,"percentInternational":13.1,"demographics":{"white":40.6,"asian":22.4,"hispanic":10.4,"black":4.8,"multiracial":6.8,"international":13.1,"other":1.8},"genderBreakdown":{"male":42.8,"female":57}},
  },
  "Northwestern University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://www.enrollment.northwestern.edu/data/2024-2025.pdf",
    data: {"acceptanceRate":7.7,"sat25":1510,"sat75":1560,"act25":34,"act75":35,"yield":55.3,"edAdmitRate":23,"studentFacultyRatio":6,"fourYearGradRate":83.4,"undergradPopulation":9060,"inStatePercent":21,"percentInternational":11.8,"demographics":{"white":30.2,"asian":21.3,"hispanic":15.7,"black":8.3,"multiracial":7.9,"international":11.8,"other":4.6},"genderBreakdown":{"male":45.9,"female":53.9}},
  },
  "Ohio State University": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://irp.osu.edu/sites/default/files/documents/2026/03/CDS-2025-2026-OSU-Columbus-Campus.pdf",
    data: {"acceptanceRate":49.2,"sat25":1300,"sat75":1440,"act25":27,"act75":32,"yield":20.6,"top10HSPercent":73,"pctTopTenClass":73,"studentFacultyRatio":13,"fourYearGradRate":71.2,"undergradPopulation":46627,"inStatePercent":72,"percentInternational":7.1,"demographics":{"white":58,"asian":11.6,"hispanic":6.3,"black":8.5,"multiracial":5.1,"international":7.1,"other":3.4},"genderBreakdown":{"male":49.4,"female":50.6}},
  },
  "Princeton University": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://ir.princeton.edu/sites/g/files/toruqf2041/files/documents/CDS_2526_Princeton_v1.3.pdf",
    data: {"acceptanceRate":4.4,"sat25":1490,"sat75":1560,"act25":34,"act75":35,"yield":75.4,"avgGPACDS":3.96,"studentFacultyRatio":8,"fourYearGradRate":72.8,"undergradPopulation":5916,"inStatePercent":16,"percentInternational":13.3,"demographics":{"white":31,"asian":25,"hispanic":9.5,"black":7.8,"multiracial":7.2,"international":13.3,"other":6.4},"genderBreakdown":{"male":49.6,"female":50.3}},
  },
  "Rice University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://ideas.rice.edu/wp-content/uploads/2025/10/CDS_2024-25_WEBSITE.pdf",
    data: {"acceptanceRate":8,"sat25":1510,"sat75":1560,"act25":34,"act75":35,"yield":44.2,"edAdmitRate":16.8,"regularDecisionAdmitRate":7.1,"top10HSPercent":89,"pctTopTenClass":89,"studentFacultyRatio":5.83,"fourYearGradRate":86.9,"undergradPopulation":4789,"inStatePercent":43,"percentInternational":13,"demographics":{"white":25.5,"asian":29,"hispanic":16.6,"black":7.9,"multiracial":5.5,"international":13,"other":2.3},"genderBreakdown":{"male":50.4,"female":49.6}},
  },
  "Rutgers University": {
    cdsYear: "2023-2024",
    sourcePdfUrl: "New Brunswick CDS_2023-2024_final_V1.pdf",
    data: {"acceptanceRate":65.4,"yield":27.1,"sat25":1270,"sat75":1480,"act25":28,"act75":33,"top10HSPercent":30,"pctTopTenClass":30,"studentFacultyRatio":15,"fourYearGradRate":71.4,"undergradPopulation":36588,"inStatePercent":84.4,"percentInternational":6.9,"demographics":{"white":31.5,"asian":33.3,"hispanic":15.6,"black":6.7,"multiracial":3.6,"international":6.9,"other":2.4},"genderBreakdown":{"male":49.9,"female":50.2}},
  },
  "Santa Clara University": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://www.scu.edu/media/offices/institutional-research/fampf/common-data-set/Common-Data-Set-2025-2026.pdf",
    data: {"acceptanceRate":47.9,"sat25":1330,"sat75":1470,"act25":29,"act75":33,"yield":17.1,"edAdmitRate":76.4,"avgGPACDS":3.72,"top10HSPercent":47,"pctTopTenClass":47,"studentFacultyRatio":11,"fourYearGradRate":80.6,"undergradPopulation":6695,"inStatePercent":62,"percentInternational":7.1,"demographics":{"white":35.6,"asian":22.2,"hispanic":20.8,"black":3.1,"multiracial":9.3,"international":7.1,"other":1.9},"genderBreakdown":{"male":49.9,"female":50.1}},
  },
  "Stanford University": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://drive.usercontent.google.com/download?id=1GIPKgVj1d86dkmLkHI_mZVCk_iY6kiCp&export=download",
    data: {"acceptanceRate":3.8,"sat25":1520,"sat75":1570,"act25":34,"act75":36,"yield":79.9,"avgGPACDS":3.9,"top10HSPercent":97,"pctTopTenClass":97,"studentFacultyRatio":10,"fourYearGradRate":45.3,"undergradPopulation":7346,"inStatePercent":44,"percentInternational":13.1,"demographics":{"white":23.6,"asian":30.4,"hispanic":15.7,"black":6.5,"multiracial":9,"international":13.1,"other":1},"genderBreakdown":{"male":49.1,"female":50.9}},
  },
  "Stevens Institute of Technology": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://assets.stevens.edu/mviowpldu823/3UEOxHKHu8NfqyLxwqBmZP/86f651ed176aae469c805a50cee0d4ee/CDS-2025-2026-PDF_3.12_updated.pdf",
    data: {"acceptanceRate":50.7,"sat25":1370,"sat75":1470,"act25":32,"act75":34,"yield":20.7,"edAdmitRate":69.8,"avgGPACDS":3.83,"top10HSPercent":47.5,"pctTopTenClass":47.5,"studentFacultyRatio":11,"fourYearGradRate":74.6,"undergradPopulation":4206,"inStatePercent":65.2,"percentInternational":4.1,"demographics":{"white":43.8,"asian":20.5,"hispanic":17.9,"black":3.2,"multiracial":4.6,"international":4.1,"other":5.7},"genderBreakdown":{"male":66.2,"female":33.7}},
  },
  "Swarthmore College": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://www.swarthmore.edu/sites/default/files/assets/documents/institutional-effectiveness-research-assessment/Swarthmore-CDS-2025-26.pdf",
    data: {"acceptanceRate":7.5,"sat25":1480,"sat75":1550,"act25":33,"act75":35,"yield":43.6,"edAdmitRate":17.8,"top10HSPercent":86.7,"pctTopTenClass":86.7,"studentFacultyRatio":8,"fourYearGradRate":72.4,"undergradPopulation":1631,"inStatePercent":12.8,"percentInternational":13.6,"demographics":{"white":30.2,"asian":16.7,"hispanic":16.4,"black":8.3,"multiracial":10.8,"international":13.6,"other":3.4},"genderBreakdown":{"male":47,"female":53}},
  },
  "Texas A&M University": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://abpa.tamu.edu/getattachment/3ef3380e-0c01-4ac3-bad5-185eb51fa208/CDS-PDF-2025-2026_TAMU_FINAL.pdf",
    data: {"acceptanceRate":51.7,"sat25":1160,"sat75":1390,"act25":24,"act75":32,"yield":38.4,"top10HSPercent":71.6,"pctTopTenClass":71.6,"studentFacultyRatio":20,"fourYearGradRate":62.8,"undergradPopulation":62031,"inStatePercent":94.8,"percentInternational":1,"demographics":{"white":49.9,"asian":14.7,"hispanic":26.5,"black":2.6,"multiracial":3.9,"international":1,"other":1.4},"genderBreakdown":{"male":52.4,"female":47.6}},
  },
  "Trinity College": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://www.trincoll.edu/asic/wp-content/uploads/sites/125/2025/12/CDS-2024-2025-Trinity-College.pdf",
    data: {"acceptanceRate":29.2,"sat25":1340,"sat75":1453,"act25":30,"act75":34,"yield":24.8,"top10HSPercent":53,"pctTopTenClass":53,"studentFacultyRatio":9,"fourYearGradRate":77.9,"undergradPopulation":2204,"inStatePercent":18,"percentInternational":13.7,"demographics":{"white":58.7,"asian":4.4,"hispanic":10.3,"black":6.1,"multiracial":4.6,"international":13.7,"other":2.2},"genderBreakdown":{"male":46.9,"female":53.1}},
  },
  "Tufts University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://provost.tufts.edu/institutionalresearch/wp-content/uploads/sites/5/CDS_2024-2025-1.pdf",
    data: {"acceptanceRate":11.5,"sat25":1480,"sat75":1540,"act25":33,"act75":35,"yield":38.4,"top10HSPercent":85,"pctTopTenClass":85,"studentFacultyRatio":10,"fourYearGradRate":82.6,"undergradPopulation":7126,"inStatePercent":29,"percentInternational":12.5,"demographics":{"white":40.6,"asian":16.7,"hispanic":10.2,"black":6.1,"multiracial":7.8,"international":12.5,"other":6},"genderBreakdown":{"male":42.5,"female":55.3}},
  },
  "UC Berkeley": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "CDS 2025-26 UC Berkeley (March 20).xlsx",
    data: {"acceptanceRate":11.4,"yield":46,"avgGPACDS":3.9,"fourYearGradRate":81.3,"undergradPopulation":33513,"percentInternational":9.8,"demographics":{"white":19.1,"asian":35.3,"hispanic":22.6,"black":1.9,"multiracial":7,"international":9.8,"other":4.3},"genderBreakdown":{"male":44.5,"female":55.5},"oosAcceptanceRate":7.3,"inStateAcceptanceRate":14.9},
  },
  "UC Merced": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "cds_2025-26_uc_merced.xlsx",
    data: {"acceptanceRate":97,"yield":4.3,"avgGPACDS":3.59,"studentFacultyRatio":22.3,"fourYearGradRate":51.3,"undergradPopulation":8234,"inStatePercent":98.5,"percentInternational":0.9,"demographics":{"white":9.4,"asian":22.4,"hispanic":55.2,"black":5,"multiracial":4.9,"international":0.9,"other":2.2},"genderBreakdown":{"male":54.1,"female":41.8}},
  },
  "UC Riverside": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "UC_Riverside_cds-2024-2025.pdf",
    data: {"acceptanceRate":76.9,"yield":12.2,"avgGPACDS":3.83,"studentFacultyRatio":22.3,"fourYearGradRate":65.4,"undergradPopulation":22599,"inStatePercent":94.8,"percentInternational":3.4,"demographics":{"white":10.3,"asian":35.9,"hispanic":40,"black":3.5,"multiracial":5,"international":3.4,"other":1.7},"genderBreakdown":{"male":46,"female":51.1}},
  },
  "UC San Diego": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://ir.ucsd.edu/stats/undergrad/CDS_2024-2025_Final1.pdf",
    data: {"acceptanceRate":28.6,"yield":20,"avgGPACDS":3.88,"top10HSPercent":100,"pctTopTenClass":100,"fourYearGradRate":74.2,"undergradPopulation":35442,"inStatePercent":91,"percentInternational":12.1,"demographics":{"white":16,"asian":34.6,"hispanic":26.8,"black":1.6,"multiracial":6.4,"international":12.1,"other":2.4},"genderBreakdown":{"male":44.5,"female":53.4}},
  },
  "UNC Chapel Hill": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://oira.unc.edu/wp-content/uploads/sites/297/2025/08/CDS_UNCCH_2024-25_20250829.pdf",
    data: {"acceptanceRate":15.3,"oosAcceptanceRate":6.6,"inStateAcceptanceRate":38,"sat25":1400,"sat75":1530,"act25":28,"act75":34,"yield":45.4,"avgGPACDS":4.49,"top10HSPercent":77,"pctTopTenClass":77,"studentFacultyRatio":15,"fourYearGradRate":83.6,"undergradPopulation":21075,"inStatePercent":85,"percentInternational":6.4,"demographics":{"white":52.8,"asian":15.9,"hispanic":9.6,"black":7.3,"multiracial":5,"international":6.4,"other":2.9},"genderBreakdown":{"male":39.3,"female":60.7}},
  },
  "UT Austin": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "UT_Austin_CDS_2025-2025.pdf",
    data: {"acceptanceRate":26.6,"oosAcceptanceRate":10.1,"inStateAcceptanceRate":37.7,"yield":47.4,"studentFacultyRatio":18,"fourYearGradRate":73.5,"undergradPopulation":43165,"inStatePercent":87.4,"percentInternational":4.5,"demographics":{"white":30.4,"asian":25.6,"hispanic":28.3,"black":4.6,"multiracial":4.1,"international":4.5,"other":2.6},"genderBreakdown":{"male":42.2,"female":57.7}},
  },
  "University at Buffalo": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "university_of_buffalo_CDS_2025-2026.pdf",
    data: {"acceptanceRate":80.6,"yield":14,"sat25":1220,"sat75":1390,"act25":27,"act75":31,"studentFacultyRatio":12,"fourYearGradRate":58,"undergradPopulation":21192,"inStatePercent":87.9,"percentInternational":11.1,"demographics":{"white":41.1,"asian":18.5,"hispanic":10.1,"black":9.9,"multiracial":4.3,"international":11.1,"other":3.7},"genderBreakdown":{"male":53.8,"female":46.2}},
  },
  "University of Alabama": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://oira.ua.edu/d/sites/all/files/reports26/CDS%202025-26%20FINAL%209Dec2025.pdf",
    data: {"acceptanceRate":71.2,"sat25":1100,"sat75":1360,"act25":22,"act75":31,"yield":18.4,"avgGPACDS":3.85,"top10HSPercent":23,"pctTopTenClass":23,"studentFacultyRatio":19,"fourYearGradRate":58.1,"undergradPopulation":35621,"inStatePercent":41.7,"percentInternational":1.1,"demographics":{"white":68.9,"asian":1.5,"hispanic":7.8,"black":12.9,"multiracial":3.8,"international":1.1,"other":3.9},"genderBreakdown":{"male":43.3,"female":56.7}},
  },
  "University of Arizona": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://uair.arizona.edu/sites/default/files/2025-03/CDS-2024-2025-FINAL.pdf",
    data: {"acceptanceRate":86.1,"sat25":1130,"sat75":1340,"act25":21,"act75":28,"yield":18.4,"avgGPACDS":3.47,"top10HSPercent":33,"pctTopTenClass":33,"studentFacultyRatio":20,"fourYearGradRate":49.9,"undergradPopulation":45025,"inStatePercent":52,"percentInternational":3.8,"demographics":{"white":44.2,"asian":4.6,"hispanic":26.9,"black":4.2,"multiracial":5.1,"international":3.8,"other":11.2},"genderBreakdown":{"male":44.5,"female":55.5}},
  },
  "University of Chicago": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://data.uchicago.edu/files/2025/08/CDS_2024-2025_to_publish.pdf",
    data: {"acceptanceRate":4.5,"sat25":1510,"sat75":1560,"act25":34,"act75":35,"yield":89.7,"avgGPACDS":4.97,"top10HSPercent":96,"pctTopTenClass":96,"studentFacultyRatio":5,"fourYearGradRate":87.2,"undergradPopulation":7519,"inStatePercent":15,"percentInternational":17.7,"demographics":{"white":29.5,"asian":19.4,"hispanic":16.8,"black":6.9,"multiracial":7,"international":17.7,"other":2.8},"genderBreakdown":{"male":54.3,"female":45.7}},
  },
  "University of Connecticut": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://bpir.media.uconn.edu/wp-content/uploads/sites/3452/2025/07/UConn_CDS_2024_2025.pdf",
    data: {"acceptanceRate":52.4,"sat25":1220,"sat75":1420,"act25":28,"act75":33,"yield":16.2,"top10HSPercent":47.2,"pctTopTenClass":47.2,"studentFacultyRatio":17,"fourYearGradRate":72.9,"undergradPopulation":20056,"inStatePercent":70,"percentInternational":7.4,"demographics":{"white":50.1,"asian":12.4,"hispanic":16.5,"black":7.5,"multiracial":4.7,"international":7.4,"other":0.7},"genderBreakdown":{"male":45,"female":55}},
  },
  "University of Florida": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://data-apps.ir.aa.ufl.edu/public/cds/CDS_2024-2025_UFMAIN_Post_v4_ADA5.pdf",
    data: {"acceptanceRate":24.2,"sat25":1330,"sat75":1470,"act25":29,"act75":33,"yield":42.2,"avgGPACDS":3.92,"top10HSPercent":84,"pctTopTenClass":84,"studentFacultyRatio":16,"fourYearGradRate":75.7,"undergradPopulation":36573,"inStatePercent":87.4,"percentInternational":3,"demographics":{"white":48.7,"asian":12.2,"hispanic":24.5,"black":4.9,"multiracial":5,"international":3,"other":1.7},"genderBreakdown":{"male":45.3,"female":54.7}},
  },
  "University of Georgia": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "http://oir.uga.edu/wp-content/uploads/UGA_CDS_2024-2025.pdf",
    data: {"acceptanceRate":37.9,"sat25":1220,"sat75":1400,"act25":26,"act75":32,"yield":38.3,"avgGPACDS":4.15,"studentFacultyRatio":17,"fourYearGradRate":75.8,"undergradPopulation":32399,"inStatePercent":80,"percentInternational":1.3,"demographics":{"white":65.6,"asian":13.4,"hispanic":7.9,"black":5.9,"multiracial":4.4,"international":1.3,"other":1.4},"genderBreakdown":{"male":41.5,"female":58.5}},
  },
  "University of Iowa": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://provost.uiowa.edu/sites/provost.uiowa.edu/files/2026-04/CDS_2526.pdf",
    data: {"acceptanceRate":79.9,"sat25":1130,"sat75":1320,"act25":21,"act75":28,"yield":22.1,"avgGPACDS":3.86,"studentFacultyRatio":17,"fourYearGradRate":60.7,"undergradPopulation":23407,"inStatePercent":57,"percentInternational":1.1,"demographics":{"white":74.2,"asian":4.2,"hispanic":8.7,"black":2.7,"multiracial":3.9,"international":1.1,"other":5},"genderBreakdown":{"male":42.6,"female":57.4}},
  },
  "University of Miami": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "UMiami_CDS.pdf",
    data: {"acceptanceRate":17.6,"yield":26.2,"edAdmitRate":44.3,"sat25":1350,"sat75":1450,"act25":30,"act75":33,"avgGPACDS":3.75,"top10HSPercent":55,"pctTopTenClass":55,"studentFacultyRatio":11,"fourYearGradRate":71.5,"undergradPopulation":13241,"inStatePercent":29.5,"percentInternational":7.4,"demographics":{"white":46.6,"asian":4.9,"hispanic":26.6,"black":6.4,"multiracial":4.7,"international":7.4,"other":3.4},"genderBreakdown":{"male":44.4,"female":55.6}},
  },
  "University of Michigan": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "firstyearsprofile_umaa_2025 (1).pdf",
    data: {"acceptanceRate":15.6,"yield":47.3,"sat25":1360,"sat75":1530,"act25":31,"act75":34,"avgGPACDS":3.95,"inStatePercent":52.9,"percentInternational":4.2,"demographics":{"white":44.8,"asian":18.2,"hispanic":14.8,"black":6.3,"multiracial":6.7,"international":4.2,"other":5.1},"genderBreakdown":{"male":43.9,"female":56}},
  },
  "University of Minnesota": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://idr.umn.edu/sites/idr.umn.edu/files/cds_2024_2025_tc_1.pdf",
    data: {"acceptanceRate":79.7,"sat25":1320,"sat75":1470,"act25":26,"act75":31,"yield":22.3,"top10HSPercent":36.3,"pctTopTenClass":36.3,"studentFacultyRatio":17,"fourYearGradRate":75.1,"undergradPopulation":41303,"inStatePercent":74.5,"percentInternational":6.2,"demographics":{"white":56.8,"asian":13.4,"hispanic":6.5,"black":9.9,"multiracial":5.1,"international":6.2,"other":0.4},"genderBreakdown":{"male":43.6,"female":55.5}},
  },
  "University of Pennsylvania": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://upenn.app.box.com/shared/static/ckv4frz37rzxa4u6bdiv2h4yzykqm4ef.pdf",
    data: {"acceptanceRate":5.4,"sat25":1510,"sat75":1570,"act25":34,"act75":36,"yield":68,"edAdmitRate":14.2,"avgGPACDS":3.9,"top10HSPercent":91,"pctTopTenClass":91,"studentFacultyRatio":8,"fourYearGradRate":86.5,"undergradPopulation":10013,"inStatePercent":18,"percentInternational":13.3,"demographics":{"white":25.8,"asian":29.6,"hispanic":11.6,"black":8.7,"multiracial":5.4,"international":13.3,"other":5.6},"genderBreakdown":{"male":45.9,"female":54.1}},
  },
  "University of Pittsburgh": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://www.ir.pitt.edu/sites/default/files/assets/2024-2025_CDS_Pittsburgh_0.pdf",
    data: {"acceptanceRate":58.1,"sat25":1280,"sat75":1460,"act25":29,"act75":33,"yield":13,"avgGPACDS":4.08,"top10HSPercent":41,"pctTopTenClass":41,"studentFacultyRatio":13,"fourYearGradRate":71.6,"undergradPopulation":20418,"inStatePercent":65,"percentInternational":4.3,"demographics":{"white":61.3,"asian":15.1,"hispanic":6.9,"black":5.3,"multiracial":4.8,"international":4.3,"other":2.3},"genderBreakdown":{"male":42,"female":58}},
  },
  "University of Rochester": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://www.rochester.edu/provost/wp-content/uploads/2025/10/CDS_2024-2025-completed-for-web-10.27.25.pdf",
    data: {"acceptanceRate":40.1,"sat25":1420,"sat75":1500,"act25":32,"act75":34,"yield":15.3,"edAdmitRate":38,"avgGPACDS":3.72,"top10HSPercent":71,"pctTopTenClass":71,"studentFacultyRatio":8.8,"fourYearGradRate":74.6,"undergradPopulation":6580,"inStatePercent":42,"percentInternational":22.1,"demographics":{"white":38.6,"asian":17.6,"hispanic":8.1,"black":5.6,"multiracial":4.3,"international":22.1,"other":3.6},"genderBreakdown":{"male":47,"female":52.6}},
  },
  "University of South Florida": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://www.usf.edu/ods/documents/cds/usf-cds-2025-2026-final-v2.pdf",
    data: {"acceptanceRate":40.7,"sat25":1160,"sat75":1340,"act25":25,"act75":29,"yield":23.1,"avgGPACDS":4.09,"top10HSPercent":29.1,"pctTopTenClass":29.1,"studentFacultyRatio":22,"fourYearGradRate":65.7,"undergradPopulation":39093,"inStatePercent":87.9,"percentInternational":7.5,"demographics":{"white":42.5,"asian":9.1,"hispanic":25.1,"black":8,"multiracial":4.7,"international":7.5,"other":0.3},"genderBreakdown":{"male":43.4,"female":56.5}},
  },
  "University of Virginia": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://ira.virginia.edu/sites/g/files/jsddwu1106/files/2025-03/CDS_2024-2025_508.pdf",
    data: {"acceptanceRate":16.8,"sat25":1410,"sat75":1520,"act25":32,"act75":35,"yield":40,"edAdmitRate":27.9,"top10HSPercent":84,"pctTopTenClass":84,"studentFacultyRatio":14,"fourYearGradRate":92.3,"undergradPopulation":17567,"inStatePercent":70,"percentInternational":4.9,"demographics":{"white":48.8,"asian":19.7,"hispanic":7.8,"black":7.5,"multiracial":5.8,"international":4.9,"other":5.3},"genderBreakdown":{"male":43.8,"female":56.1},"oosAcceptanceRate":13.8,"inStateAcceptanceRate":25.9},
  },
  "University of Washington": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://uw-s3-cdn.s3.us-west-2.amazonaws.com/wp-content/uploads/sites/162/2026/02/27111247/CDS_2025-2026_Seattle.pdf",
    data: {"acceptanceRate":41.7,"sat25":1320,"sat75":1502,"act25":30,"act75":34,"yield":23.4,"avgGPACDS":3.84,"studentFacultyRatio":21,"fourYearGradRate":74.6,"undergradPopulation":40996,"inStatePercent":76.9,"percentInternational":8.9,"demographics":{"white":32.9,"asian":24.6,"hispanic":11,"black":4.1,"multiracial":8.2,"international":8.9,"other":9.8},"genderBreakdown":{"male":43.7,"female":55.2}},
  },
  "Vanderbilt University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://cdn.vanderbilt.edu/vu-wpfsx/wp-content/uploads/sites/70/2025/11/CDS_2024-2025.xlsx",
    data: {"acceptanceRate":5.9,"sat25":1510,"sat75":1560,"act25":34,"act75":35,"yield":61.2,"edAdmitRate":15.4,"avgGPACDS":3.89,"top10HSPercent":90,"pctTopTenClass":90,"studentFacultyRatio":8,"fourYearGradRate":89.8,"undergradPopulation":7221,"inStatePercent":12,"percentInternational":11.2,"demographics":{"white":39,"asian":18.5,"hispanic":11.4,"black":9.2,"multiracial":5.7,"international":11.2,"other":0.7},"genderBreakdown":{"male":47.6,"female":52.4}},
  },
  "Virginia Tech": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://aie.vt.edu/content/dam/aie_vt_edu/common-data-set/25-26/2025-2026-CDS.xlsx",
    data: {"acceptanceRate":54.6,"sat25":1280,"sat75":1450,"act25":28,"act75":32,"yield":22.6,"avgGPACDS":4.06,"studentFacultyRatio":17,"fourYearGradRate":68.9,"undergradPopulation":31536,"inStatePercent":69,"percentInternational":5.4,"demographics":{"white":55.3,"asian":14.2,"hispanic":10.1,"black":5.7,"multiracial":6,"international":5.4,"other":0.1},"genderBreakdown":{"male":56.2,"female":43.5}},
  },
  "Wake Forest University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://prod.wp.cdn.aws.wfu.edu/sites/202/2025/07/CDS-2024-2025-fillable-WFU.pdf",
    data: {"acceptanceRate":21.6,"sat25":1420,"sat75":1500,"act25":32,"act75":34,"yield":36.1,"top10HSPercent":64.2,"pctTopTenClass":64.2,"studentFacultyRatio":10,"fourYearGradRate":84.2,"undergradPopulation":5490,"inStatePercent":12.7,"percentInternational":5.8,"demographics":{"white":65.1,"asian":5.3,"hispanic":9.7,"black":6.4,"multiracial":4.6,"international":5.8,"other":3},"genderBreakdown":{"male":44.9,"female":55.1}},
  },
  "Washington University in St. Louis": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://washu.edu/app/uploads/2025/06/2024-2025-WashU-CDS.pdf",
    data: {"acceptanceRate":12.1,"sat25":1500,"sat75":1570,"act25":33,"act75":35,"yield":46.7,"edAdmitRate":25.3,"avgGPACDS":4.19,"top10HSPercent":86,"pctTopTenClass":86,"studentFacultyRatio":7,"fourYearGradRate":85.1,"undergradPopulation":8220,"inStatePercent":13,"percentInternational":9.4,"demographics":{"white":39.6,"asian":20.3,"hispanic":12.9,"black":9.3,"multiracial":6,"international":9.4,"other":2.4},"genderBreakdown":{"male":44.7,"female":55.3}},
  },
  "Wellesley College": {
    cdsYear: "2025-2026",
    sourcePdfUrl: "https://wellesley-college.files.svdcdn.com/production/administrative-departments/OIR/CDS_2025-2026-FINAL.pdf?dm=1773253066",
    data: {"acceptanceRate":14.8,"sat25":1460,"sat75":1540,"act25":33,"act75":35,"yield":45.8,"edAdmitRate":29.4,"regularDecisionAdmitRate":12.8,"top10HSPercent":88,"pctTopTenClass":88,"studentFacultyRatio":8,"fourYearGradRate":78.6,"undergradPopulation":2366,"inStatePercent":14,"percentInternational":13,"demographics":{"white":29.8,"asian":27.7,"hispanic":12.8,"black":7.1,"multiracial":7.6,"international":13,"other":1.9},"genderBreakdown":{"male":1.3,"female":98.4}},
  },
  "Worcester Polytechnic Institute": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "WPI_CDS_2024-2025_2-27-25.pdf",
    data: {"acceptanceRate":60.2,"yield":18.1,"edAdmitRate":75.6,"avgGPACDS":3.9,"top10HSPercent":56,"pctTopTenClass":56,"studentFacultyRatio":13,"fourYearGradRate":84.4,"undergradPopulation":5558,"inStatePercent":46.9,"percentInternational":6.4,"demographics":{"white":63.1,"asian":12.5,"hispanic":8.4,"black":2.7,"multiracial":3.5,"international":6.4,"other":3.5},"genderBreakdown":{"male":67.3,"female":32.7}},
  },
  "Yale University": {
    cdsYear: "2024-2025",
    sourcePdfUrl: "https://oir.yale.edu/sites/default/files/yale_cds_2024-25_rmd_20250612.pdf",
    data: {"acceptanceRate":3.9,"sat25":1480,"sat75":1560,"act25":33,"act75":35,"yield":69.8,"top10HSPercent":96,"pctTopTenClass":96,"studentFacultyRatio":5,"fourYearGradRate":57.5,"undergradPopulation":6814,"inStatePercent":7,"percentInternational":11.1,"demographics":{"white":31,"asian":21.8,"hispanic":16.5,"black":9.2,"multiracial":7,"international":11.1,"other":0.6},"genderBreakdown":{"male":48.5,"female":50.1}},
  },
  "Yeshiva University": {
    cdsYear: "2023-2024",
    sourcePdfUrl: "yeshiva_university_CDS_2023_2024.xlsx",
    data: {"acceptanceRate":63.8,"yield":59,"edAdmitRate":100,"sat25":1330,"sat75":1470,"act25":28,"act75":33,"avgGPACDS":3.5,"studentFacultyRatio":7,"fourYearGradRate":79.4,"undergradPopulation":2334,"percentInternational":7.7,"demographics":{"white":53.7,"asian":0.1,"hispanic":2.1,"black":0.2,"multiracial":0.5,"international":7.7,"other":35.7},"genderBreakdown":{"male":54.8,"female":45.2}},
  },
};
